// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: emailtemplate-grpc.proto

package emailtemplate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmailTemplateService_Get_FullMethodName    = "/emailtemplate.EmailTemplateService/Get"
	EmailTemplateService_List_FullMethodName   = "/emailtemplate.EmailTemplateService/List"
	EmailTemplateService_Upsert_FullMethodName = "/emailtemplate.EmailTemplateService/Upsert"
	EmailTemplateService_Delete_FullMethodName = "/emailtemplate.EmailTemplateService/Delete"
)

// EmailTemplateServiceClient is the client API for EmailTemplateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmailTemplateServiceClient interface {
	Get(ctx context.Context, in *EmailTemplateID, opts ...grpc.CallOption) (*EmailTemplate, error)
	List(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*EmailTemplates, error)
	Upsert(ctx context.Context, in *EmailTemplate, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Use cases:
	// 1. Delete a system template (Sologenic Admin only)
	// 2. Delete an organization specific template to revert to default system template (Organization Admin only)
	Delete(ctx context.Context, in *EmailTemplate, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type emailTemplateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailTemplateServiceClient(cc grpc.ClientConnInterface) EmailTemplateServiceClient {
	return &emailTemplateServiceClient{cc}
}

func (c *emailTemplateServiceClient) Get(ctx context.Context, in *EmailTemplateID, opts ...grpc.CallOption) (*EmailTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailTemplate)
	err := c.cc.Invoke(ctx, EmailTemplateService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailTemplateServiceClient) List(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*EmailTemplates, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailTemplates)
	err := c.cc.Invoke(ctx, EmailTemplateService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailTemplateServiceClient) Upsert(ctx context.Context, in *EmailTemplate, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmailTemplateService_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailTemplateServiceClient) Delete(ctx context.Context, in *EmailTemplate, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmailTemplateService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailTemplateServiceServer is the server API for EmailTemplateService service.
// All implementations should embed UnimplementedEmailTemplateServiceServer
// for forward compatibility.
type EmailTemplateServiceServer interface {
	Get(context.Context, *EmailTemplateID) (*EmailTemplate, error)
	List(context.Context, *Filter) (*EmailTemplates, error)
	Upsert(context.Context, *EmailTemplate) (*emptypb.Empty, error)
	// Use cases:
	// 1. Delete a system template (Sologenic Admin only)
	// 2. Delete an organization specific template to revert to default system template (Organization Admin only)
	Delete(context.Context, *EmailTemplate) (*emptypb.Empty, error)
}

// UnimplementedEmailTemplateServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmailTemplateServiceServer struct{}

func (UnimplementedEmailTemplateServiceServer) Get(context.Context, *EmailTemplateID) (*EmailTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedEmailTemplateServiceServer) List(context.Context, *Filter) (*EmailTemplates, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedEmailTemplateServiceServer) Upsert(context.Context, *EmailTemplate) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedEmailTemplateServiceServer) Delete(context.Context, *EmailTemplate) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedEmailTemplateServiceServer) testEmbeddedByValue() {}

// UnsafeEmailTemplateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailTemplateServiceServer will
// result in compilation errors.
type UnsafeEmailTemplateServiceServer interface {
	mustEmbedUnimplementedEmailTemplateServiceServer()
}

func RegisterEmailTemplateServiceServer(s grpc.ServiceRegistrar, srv EmailTemplateServiceServer) {
	// If the following call pancis, it indicates UnimplementedEmailTemplateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmailTemplateService_ServiceDesc, srv)
}

func _EmailTemplateService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailTemplateID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailTemplateServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailTemplateService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailTemplateServiceServer).Get(ctx, req.(*EmailTemplateID))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailTemplateService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailTemplateServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailTemplateService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailTemplateServiceServer).List(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailTemplateService_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailTemplate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailTemplateServiceServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailTemplateService_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailTemplateServiceServer).Upsert(ctx, req.(*EmailTemplate))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailTemplateService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailTemplate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailTemplateServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailTemplateService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailTemplateServiceServer).Delete(ctx, req.(*EmailTemplate))
	}
	return interceptor(ctx, in, info, handler)
}

// EmailTemplateService_ServiceDesc is the grpc.ServiceDesc for EmailTemplateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailTemplateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emailtemplate.EmailTemplateService",
	HandlerType: (*EmailTemplateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _EmailTemplateService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _EmailTemplateService_List_Handler,
		},
		{
			MethodName: "Upsert",
			Handler:    _EmailTemplateService_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _EmailTemplateService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emailtemplate-grpc.proto",
}
