// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: emailtemplate-grpc.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal";
import {
  EmailTemplate,
  EmailTemplates,
  EmailTemplateType,
  emailTemplateTypeFromJSON,
  emailTemplateTypeToJSON,
} from "./emailtemplate";
import { Empty } from "./google/protobuf/empty";
import { Network, networkFromJSON, networkToJSON } from "./sologenic/com-fs-utils-lib/models/metadata/metadata";

export const protobufPackage = "emailtemplate";

export interface EmailTemplateID {
  EmailTemplateType: EmailTemplateType;
  OrganizationID?: string | undefined;
  Network?: Network | undefined;
}

export interface Filter {
  Type?: EmailTemplateType | undefined;
  OrganizationID?: string | undefined;
  Network?: Network | undefined;
}

function createBaseEmailTemplateID(): EmailTemplateID {
  return { EmailTemplateType: 0, OrganizationID: undefined, Network: undefined };
}

export const EmailTemplateID = {
  encode(message: EmailTemplateID, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.EmailTemplateType !== 0) {
      writer.uint32(8).int32(message.EmailTemplateType);
    }
    if (message.OrganizationID !== undefined) {
      writer.uint32(18).string(message.OrganizationID);
    }
    if (message.Network !== undefined) {
      writer.uint32(24).int32(message.Network);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): EmailTemplateID {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmailTemplateID();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.EmailTemplateType = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmailTemplateID {
    return {
      EmailTemplateType: isSet(object.EmailTemplateType) ? emailTemplateTypeFromJSON(object.EmailTemplateType) : 0,
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : undefined,
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : undefined,
    };
  },

  toJSON(message: EmailTemplateID): unknown {
    const obj: any = {};
    if (message.EmailTemplateType !== 0) {
      obj.EmailTemplateType = emailTemplateTypeToJSON(message.EmailTemplateType);
    }
    if (message.OrganizationID !== undefined) {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.Network !== undefined) {
      obj.Network = networkToJSON(message.Network);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmailTemplateID>, I>>(base?: I): EmailTemplateID {
    return EmailTemplateID.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmailTemplateID>, I>>(object: I): EmailTemplateID {
    const message = createBaseEmailTemplateID();
    message.EmailTemplateType = object.EmailTemplateType ?? 0;
    message.OrganizationID = object.OrganizationID ?? undefined;
    message.Network = object.Network ?? undefined;
    return message;
  },
};

function createBaseFilter(): Filter {
  return { Type: undefined, OrganizationID: undefined, Network: undefined };
}

export const Filter = {
  encode(message: Filter, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Type !== undefined) {
      writer.uint32(8).int32(message.Type);
    }
    if (message.OrganizationID !== undefined) {
      writer.uint32(18).string(message.OrganizationID);
    }
    if (message.Network !== undefined) {
      writer.uint32(24).int32(message.Network);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Filter {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFilter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.Type = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Filter {
    return {
      Type: isSet(object.Type) ? emailTemplateTypeFromJSON(object.Type) : undefined,
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : undefined,
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : undefined,
    };
  },

  toJSON(message: Filter): unknown {
    const obj: any = {};
    if (message.Type !== undefined) {
      obj.Type = emailTemplateTypeToJSON(message.Type);
    }
    if (message.OrganizationID !== undefined) {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.Network !== undefined) {
      obj.Network = networkToJSON(message.Network);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Filter>, I>>(base?: I): Filter {
    return Filter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Filter>, I>>(object: I): Filter {
    const message = createBaseFilter();
    message.Type = object.Type ?? undefined;
    message.OrganizationID = object.OrganizationID ?? undefined;
    message.Network = object.Network ?? undefined;
    return message;
  },
};

export type EmailTemplateServiceService = typeof EmailTemplateServiceService;
export const EmailTemplateServiceService = {
  get: {
    path: "/emailtemplate.EmailTemplateService/Get",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: EmailTemplateID) => Buffer.from(EmailTemplateID.encode(value).finish()),
    requestDeserialize: (value: Buffer) => EmailTemplateID.decode(value),
    responseSerialize: (value: EmailTemplate) => Buffer.from(EmailTemplate.encode(value).finish()),
    responseDeserialize: (value: Buffer) => EmailTemplate.decode(value),
  },
  list: {
    path: "/emailtemplate.EmailTemplateService/List",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Filter) => Buffer.from(Filter.encode(value).finish()),
    requestDeserialize: (value: Buffer) => Filter.decode(value),
    responseSerialize: (value: EmailTemplates) => Buffer.from(EmailTemplates.encode(value).finish()),
    responseDeserialize: (value: Buffer) => EmailTemplates.decode(value),
  },
  upsert: {
    path: "/emailtemplate.EmailTemplateService/Upsert",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: EmailTemplate) => Buffer.from(EmailTemplate.encode(value).finish()),
    requestDeserialize: (value: Buffer) => EmailTemplate.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  /**
   * Use cases:
   * 1. Delete a default template (Sologenic Admin only)
   * 2. Delete an organization specific template to revert to default (Organization Admin only)
   */
  delete: {
    path: "/emailtemplate.EmailTemplateService/Delete",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: EmailTemplate) => Buffer.from(EmailTemplate.encode(value).finish()),
    requestDeserialize: (value: Buffer) => EmailTemplate.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
} as const;

export interface EmailTemplateServiceServer extends UntypedServiceImplementation {
  get: handleUnaryCall<EmailTemplateID, EmailTemplate>;
  list: handleUnaryCall<Filter, EmailTemplates>;
  upsert: handleUnaryCall<EmailTemplate, Empty>;
  /**
   * Use cases:
   * 1. Delete a default template (Sologenic Admin only)
   * 2. Delete an organization specific template to revert to default (Organization Admin only)
   */
  delete: handleUnaryCall<EmailTemplate, Empty>;
}

export interface EmailTemplateServiceClient extends Client {
  get(
    request: EmailTemplateID,
    callback: (error: ServiceError | null, response: EmailTemplate) => void,
  ): ClientUnaryCall;
  get(
    request: EmailTemplateID,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: EmailTemplate) => void,
  ): ClientUnaryCall;
  get(
    request: EmailTemplateID,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: EmailTemplate) => void,
  ): ClientUnaryCall;
  list(request: Filter, callback: (error: ServiceError | null, response: EmailTemplates) => void): ClientUnaryCall;
  list(
    request: Filter,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: EmailTemplates) => void,
  ): ClientUnaryCall;
  list(
    request: Filter,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: EmailTemplates) => void,
  ): ClientUnaryCall;
  upsert(request: EmailTemplate, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  upsert(
    request: EmailTemplate,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  upsert(
    request: EmailTemplate,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  /**
   * Use cases:
   * 1. Delete a default template (Sologenic Admin only)
   * 2. Delete an organization specific template to revert to default (Organization Admin only)
   */
  delete(request: EmailTemplate, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  delete(
    request: EmailTemplate,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  delete(
    request: EmailTemplate,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
}

export const EmailTemplateServiceClient = makeGenericClientConstructor(
  EmailTemplateServiceService,
  "emailtemplate.EmailTemplateService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): EmailTemplateServiceClient;
  service: typeof EmailTemplateServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
