// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: emailtemplate-grpc.proto

package emailtemplate

import (
	metadata "github.com/sologenic/com-fs-utils-lib/models/metadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailTemplateID struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EmailTemplateType EmailTemplateType      `protobuf:"varint,1,opt,name=EmailTemplateType,proto3,enum=emailtemplate.EmailTemplateType" json:"EmailTemplateType,omitempty"`
	OrganizationID    *string                `protobuf:"bytes,2,opt,name=OrganizationID,proto3,oneof" json:"OrganizationID,omitempty"`
	Network           *metadata.Network      `protobuf:"varint,3,opt,name=Network,proto3,enum=metadata.Network,oneof" json:"Network,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EmailTemplateID) Reset() {
	*x = EmailTemplateID{}
	mi := &file_emailtemplate_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailTemplateID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailTemplateID) ProtoMessage() {}

func (x *EmailTemplateID) ProtoReflect() protoreflect.Message {
	mi := &file_emailtemplate_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailTemplateID.ProtoReflect.Descriptor instead.
func (*EmailTemplateID) Descriptor() ([]byte, []int) {
	return file_emailtemplate_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *EmailTemplateID) GetEmailTemplateType() EmailTemplateType {
	if x != nil {
		return x.EmailTemplateType
	}
	return EmailTemplateType_NOT_USED_EMAIL_TEMPLATE_TYPE
}

func (x *EmailTemplateID) GetOrganizationID() string {
	if x != nil && x.OrganizationID != nil {
		return *x.OrganizationID
	}
	return ""
}

func (x *EmailTemplateID) GetNetwork() metadata.Network {
	if x != nil && x.Network != nil {
		return *x.Network
	}
	return metadata.Network(0)
}

type Filter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           *EmailTemplateType     `protobuf:"varint,1,opt,name=Type,proto3,enum=emailtemplate.EmailTemplateType,oneof" json:"Type,omitempty"`
	OrganizationID *string                `protobuf:"bytes,2,opt,name=OrganizationID,proto3,oneof" json:"OrganizationID,omitempty"`
	Network        *metadata.Network      `protobuf:"varint,3,opt,name=Network,proto3,enum=metadata.Network,oneof" json:"Network,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_emailtemplate_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_emailtemplate_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_emailtemplate_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetType() EmailTemplateType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return EmailTemplateType_NOT_USED_EMAIL_TEMPLATE_TYPE
}

func (x *Filter) GetOrganizationID() string {
	if x != nil && x.OrganizationID != nil {
		return *x.OrganizationID
	}
	return ""
}

func (x *Filter) GetNetwork() metadata.Network {
	if x != nil && x.Network != nil {
		return *x.Network
	}
	return metadata.Network(0)
}

var File_emailtemplate_grpc_proto protoreflect.FileDescriptor

const file_emailtemplate_grpc_proto_rawDesc = "" +
	"\n" +
	"\x18emailtemplate-grpc.proto\x12\remailtemplate\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13emailtemplate.proto\x1a9sologenic/com-fs-utils-lib/models/metadata/metadata.proto\"\xdf\x01\n" +
	"\x0fEmailTemplateID\x12N\n" +
	"\x11EmailTemplateType\x18\x01 \x01(\x0e2 .emailtemplate.EmailTemplateTypeR\x11EmailTemplateType\x12+\n" +
	"\x0eOrganizationID\x18\x02 \x01(\tH\x00R\x0eOrganizationID\x88\x01\x01\x120\n" +
	"\aNetwork\x18\x03 \x01(\x0e2\x11.metadata.NetworkH\x01R\aNetwork\x88\x01\x01B\x11\n" +
	"\x0f_OrganizationIDB\n" +
	"\n" +
	"\b_Network\"\xca\x01\n" +
	"\x06Filter\x129\n" +
	"\x04Type\x18\x01 \x01(\x0e2 .emailtemplate.EmailTemplateTypeH\x00R\x04Type\x88\x01\x01\x12+\n" +
	"\x0eOrganizationID\x18\x02 \x01(\tH\x01R\x0eOrganizationID\x88\x01\x01\x120\n" +
	"\aNetwork\x18\x03 \x01(\x0e2\x11.metadata.NetworkH\x02R\aNetwork\x88\x01\x01B\a\n" +
	"\x05_TypeB\x11\n" +
	"\x0f_OrganizationIDB\n" +
	"\n" +
	"\b_Network2\xa1\x02\n" +
	"\x14EmailTemplateService\x12E\n" +
	"\x03Get\x12\x1e.emailtemplate.EmailTemplateID\x1a\x1c.emailtemplate.EmailTemplate\"\x00\x12>\n" +
	"\x04List\x12\x15.emailtemplate.Filter\x1a\x1d.emailtemplate.EmailTemplates\"\x00\x12@\n" +
	"\x06Upsert\x12\x1c.emailtemplate.EmailTemplate\x1a\x16.google.protobuf.Empty\"\x00\x12@\n" +
	"\x06Delete\x12\x1c.emailtemplate.EmailTemplate\x1a\x16.google.protobuf.Empty\"\x00B@Z>github.com/sologenic/com-fs-email-template-model;emailtemplateb\x06proto3"

var (
	file_emailtemplate_grpc_proto_rawDescOnce sync.Once
	file_emailtemplate_grpc_proto_rawDescData []byte
)

func file_emailtemplate_grpc_proto_rawDescGZIP() []byte {
	file_emailtemplate_grpc_proto_rawDescOnce.Do(func() {
		file_emailtemplate_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_emailtemplate_grpc_proto_rawDesc), len(file_emailtemplate_grpc_proto_rawDesc)))
	})
	return file_emailtemplate_grpc_proto_rawDescData
}

var file_emailtemplate_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_emailtemplate_grpc_proto_goTypes = []any{
	(*EmailTemplateID)(nil), // 0: emailtemplate.EmailTemplateID
	(*Filter)(nil),          // 1: emailtemplate.Filter
	(EmailTemplateType)(0),  // 2: emailtemplate.EmailTemplateType
	(metadata.Network)(0),   // 3: metadata.Network
	(*EmailTemplate)(nil),   // 4: emailtemplate.EmailTemplate
	(*EmailTemplates)(nil),  // 5: emailtemplate.EmailTemplates
	(*emptypb.Empty)(nil),   // 6: google.protobuf.Empty
}
var file_emailtemplate_grpc_proto_depIdxs = []int32{
	2, // 0: emailtemplate.EmailTemplateID.EmailTemplateType:type_name -> emailtemplate.EmailTemplateType
	3, // 1: emailtemplate.EmailTemplateID.Network:type_name -> metadata.Network
	2, // 2: emailtemplate.Filter.Type:type_name -> emailtemplate.EmailTemplateType
	3, // 3: emailtemplate.Filter.Network:type_name -> metadata.Network
	0, // 4: emailtemplate.EmailTemplateService.Get:input_type -> emailtemplate.EmailTemplateID
	1, // 5: emailtemplate.EmailTemplateService.List:input_type -> emailtemplate.Filter
	4, // 6: emailtemplate.EmailTemplateService.Upsert:input_type -> emailtemplate.EmailTemplate
	4, // 7: emailtemplate.EmailTemplateService.Delete:input_type -> emailtemplate.EmailTemplate
	4, // 8: emailtemplate.EmailTemplateService.Get:output_type -> emailtemplate.EmailTemplate
	5, // 9: emailtemplate.EmailTemplateService.List:output_type -> emailtemplate.EmailTemplates
	6, // 10: emailtemplate.EmailTemplateService.Upsert:output_type -> google.protobuf.Empty
	6, // 11: emailtemplate.EmailTemplateService.Delete:output_type -> google.protobuf.Empty
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_emailtemplate_grpc_proto_init() }
func file_emailtemplate_grpc_proto_init() {
	if File_emailtemplate_grpc_proto != nil {
		return
	}
	file_emailtemplate_proto_init()
	file_emailtemplate_grpc_proto_msgTypes[0].OneofWrappers = []any{}
	file_emailtemplate_grpc_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_emailtemplate_grpc_proto_rawDesc), len(file_emailtemplate_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_emailtemplate_grpc_proto_goTypes,
		DependencyIndexes: file_emailtemplate_grpc_proto_depIdxs,
		MessageInfos:      file_emailtemplate_grpc_proto_msgTypes,
	}.Build()
	File_emailtemplate_grpc_proto = out.File
	file_emailtemplate_grpc_proto_goTypes = nil
	file_emailtemplate_grpc_proto_depIdxs = nil
}
