// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: emailtemplate.proto

package emailtemplate

import (
	audit "github.com/sologenic/com-fs-utils-lib/models/audit"
	metadata "github.com/sologenic/com-fs-utils-lib/models/metadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailTemplateType int32

const (
	EmailTemplateType_NOT_USED_EMAIL_TEMPLATE_TYPE EmailTemplateType = 0
	// KYC Email Templates (configurable by each organization)
	// Target: End User
	EmailTemplateType_KYC_APPROVED                EmailTemplateType = 1
	EmailTemplateType_KYC_REJECTED                EmailTemplateType = 2
	EmailTemplateType_KYC_NOT_PROCESSABLE_FOREVER EmailTemplateType = 3
	EmailTemplateType_KYC_FIX_REQUEST             EmailTemplateType = 4
	EmailTemplateType_KYC_ADMIN_DENIED            EmailTemplateType = 5
	// Support ticket templates
	// Target: End User
	EmailTemplateType_SUPPORT_TICKET_SUBMITTED EmailTemplateType = 6
	// Billing
	EmailTemplateType_BILLING_LOW_BALANCE_WARNING EmailTemplateType = 7
	// Referral
	EmailTemplateType_REFERRAL_SHARED EmailTemplateType = 8 // When a user shares their referral code with someone else
	// Organization Templates
	// Target: Organization Admin
	EmailTemplateType_ORGANIZATION_ONBOARDING EmailTemplateType = 100 // Initial org admin onboarding when a new org & initial admin are created by TX admin
	EmailTemplateType_ORGANIZATION_NEW_ADMIN  EmailTemplateType = 101 // New org admin added
	// Partner Templates
	EmailTemplateType_PARTNER_ONBOARDING EmailTemplateType = 200 // Initial partner onboarding when a new partner is created by TX admin
)

// Enum value maps for EmailTemplateType.
var (
	EmailTemplateType_name = map[int32]string{
		0:   "NOT_USED_EMAIL_TEMPLATE_TYPE",
		1:   "KYC_APPROVED",
		2:   "KYC_REJECTED",
		3:   "KYC_NOT_PROCESSABLE_FOREVER",
		4:   "KYC_FIX_REQUEST",
		5:   "KYC_ADMIN_DENIED",
		6:   "SUPPORT_TICKET_SUBMITTED",
		7:   "BILLING_LOW_BALANCE_WARNING",
		8:   "REFERRAL_SHARED",
		100: "ORGANIZATION_ONBOARDING",
		101: "ORGANIZATION_NEW_ADMIN",
		200: "PARTNER_ONBOARDING",
	}
	EmailTemplateType_value = map[string]int32{
		"NOT_USED_EMAIL_TEMPLATE_TYPE": 0,
		"KYC_APPROVED":                 1,
		"KYC_REJECTED":                 2,
		"KYC_NOT_PROCESSABLE_FOREVER":  3,
		"KYC_FIX_REQUEST":              4,
		"KYC_ADMIN_DENIED":             5,
		"SUPPORT_TICKET_SUBMITTED":     6,
		"BILLING_LOW_BALANCE_WARNING":  7,
		"REFERRAL_SHARED":              8,
		"ORGANIZATION_ONBOARDING":      100,
		"ORGANIZATION_NEW_ADMIN":       101,
		"PARTNER_ONBOARDING":           200,
	}
)

func (x EmailTemplateType) Enum() *EmailTemplateType {
	p := new(EmailTemplateType)
	*p = x
	return p
}

func (x EmailTemplateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmailTemplateType) Descriptor() protoreflect.EnumDescriptor {
	return file_emailtemplate_proto_enumTypes[0].Descriptor()
}

func (EmailTemplateType) Type() protoreflect.EnumType {
	return &file_emailtemplate_proto_enumTypes[0]
}

func (x EmailTemplateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmailTemplateType.Descriptor instead.
func (EmailTemplateType) EnumDescriptor() ([]byte, []int) {
	return file_emailtemplate_proto_rawDescGZIP(), []int{0}
}

// Key: OrganizationID-Network-EmailTemplateType
type EmailTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailTemplate *EmailTemplateDetails  `protobuf:"bytes,1,opt,name=EmailTemplate,proto3" json:"EmailTemplate,omitempty"`
	Audit         *audit.Audit           `protobuf:"bytes,3,opt,name=Audit,proto3" json:"Audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailTemplate) Reset() {
	*x = EmailTemplate{}
	mi := &file_emailtemplate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailTemplate) ProtoMessage() {}

func (x *EmailTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_emailtemplate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailTemplate.ProtoReflect.Descriptor instead.
func (*EmailTemplate) Descriptor() ([]byte, []int) {
	return file_emailtemplate_proto_rawDescGZIP(), []int{0}
}

func (x *EmailTemplate) GetEmailTemplate() *EmailTemplateDetails {
	if x != nil {
		return x.EmailTemplate
	}
	return nil
}

func (x *EmailTemplate) GetAudit() *audit.Audit {
	if x != nil {
		return x.Audit
	}
	return nil
}

type EmailTemplateDetails struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           EmailTemplateType      `protobuf:"varint,1,opt,name=Type,proto3,enum=emailtemplate.EmailTemplateType" json:"Type,omitempty"`
	OrganizationID *string                `protobuf:"bytes,2,opt,name=OrganizationID,proto3,oneof" json:"OrganizationID,omitempty"` // If not set, this is a System template
	Name           string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`                           // Display Name
	Subject        string                 `protobuf:"bytes,4,opt,name=Subject,proto3" json:"Subject,omitempty"`                     // Email Subject
	HTML           string                 `protobuf:"bytes,5,opt,name=HTML,proto3" json:"HTML,omitempty"`                           // HTML content
	Description    string                 `protobuf:"bytes,6,opt,name=Description,proto3" json:"Description,omitempty"`             // Description for internal use
	PlainText      string                 `protobuf:"bytes,7,opt,name=PlainText,proto3" json:"PlainText,omitempty"`                 // fallback for HTML content
	// Non-standard metadata: Network here is optional. In other cases it is almost always required
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Network       *metadata.Network      `protobuf:"varint,10,opt,name=Network,proto3,enum=metadata.Network,oneof" json:"Network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailTemplateDetails) Reset() {
	*x = EmailTemplateDetails{}
	mi := &file_emailtemplate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailTemplateDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailTemplateDetails) ProtoMessage() {}

func (x *EmailTemplateDetails) ProtoReflect() protoreflect.Message {
	mi := &file_emailtemplate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailTemplateDetails.ProtoReflect.Descriptor instead.
func (*EmailTemplateDetails) Descriptor() ([]byte, []int) {
	return file_emailtemplate_proto_rawDescGZIP(), []int{1}
}

func (x *EmailTemplateDetails) GetType() EmailTemplateType {
	if x != nil {
		return x.Type
	}
	return EmailTemplateType_NOT_USED_EMAIL_TEMPLATE_TYPE
}

func (x *EmailTemplateDetails) GetOrganizationID() string {
	if x != nil && x.OrganizationID != nil {
		return *x.OrganizationID
	}
	return ""
}

func (x *EmailTemplateDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmailTemplateDetails) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailTemplateDetails) GetHTML() string {
	if x != nil {
		return x.HTML
	}
	return ""
}

func (x *EmailTemplateDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EmailTemplateDetails) GetPlainText() string {
	if x != nil {
		return x.PlainText
	}
	return ""
}

func (x *EmailTemplateDetails) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EmailTemplateDetails) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *EmailTemplateDetails) GetNetwork() metadata.Network {
	if x != nil && x.Network != nil {
		return *x.Network
	}
	return metadata.Network(0)
}

type EmailTemplates struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EmailTemplates []*EmailTemplate       `protobuf:"bytes,1,rep,name=EmailTemplates,proto3" json:"EmailTemplates,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EmailTemplates) Reset() {
	*x = EmailTemplates{}
	mi := &file_emailtemplate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailTemplates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailTemplates) ProtoMessage() {}

func (x *EmailTemplates) ProtoReflect() protoreflect.Message {
	mi := &file_emailtemplate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailTemplates.ProtoReflect.Descriptor instead.
func (*EmailTemplates) Descriptor() ([]byte, []int) {
	return file_emailtemplate_proto_rawDescGZIP(), []int{2}
}

func (x *EmailTemplates) GetEmailTemplates() []*EmailTemplate {
	if x != nil {
		return x.EmailTemplates
	}
	return nil
}

var File_emailtemplate_proto protoreflect.FileDescriptor

const file_emailtemplate_proto_rawDesc = "" +
	"\n" +
	"\x13emailtemplate.proto\x12\remailtemplate\x1a\x1fgoogle/protobuf/timestamp.proto\x1a3sologenic/com-fs-utils-lib/models/audit/audit.proto\x1a9sologenic/com-fs-utils-lib/models/metadata/metadata.proto\"~\n" +
	"\rEmailTemplate\x12I\n" +
	"\rEmailTemplate\x18\x01 \x01(\v2#.emailtemplate.EmailTemplateDetailsR\rEmailTemplate\x12\"\n" +
	"\x05Audit\x18\x03 \x01(\v2\f.audit.AuditR\x05Audit\"\xc0\x03\n" +
	"\x14EmailTemplateDetails\x124\n" +
	"\x04Type\x18\x01 \x01(\x0e2 .emailtemplate.EmailTemplateTypeR\x04Type\x12+\n" +
	"\x0eOrganizationID\x18\x02 \x01(\tH\x00R\x0eOrganizationID\x88\x01\x01\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x18\n" +
	"\aSubject\x18\x04 \x01(\tR\aSubject\x12\x12\n" +
	"\x04HTML\x18\x05 \x01(\tR\x04HTML\x12 \n" +
	"\vDescription\x18\x06 \x01(\tR\vDescription\x12\x1c\n" +
	"\tPlainText\x18\a \x01(\tR\tPlainText\x128\n" +
	"\tCreatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x120\n" +
	"\aNetwork\x18\n" +
	" \x01(\x0e2\x11.metadata.NetworkH\x01R\aNetwork\x88\x01\x01B\x11\n" +
	"\x0f_OrganizationIDB\n" +
	"\n" +
	"\b_Network\"V\n" +
	"\x0eEmailTemplates\x12D\n" +
	"\x0eEmailTemplates\x18\x01 \x03(\v2\x1c.emailtemplate.EmailTemplateR\x0eEmailTemplates*\xcb\x02\n" +
	"\x11EmailTemplateType\x12 \n" +
	"\x1cNOT_USED_EMAIL_TEMPLATE_TYPE\x10\x00\x12\x10\n" +
	"\fKYC_APPROVED\x10\x01\x12\x10\n" +
	"\fKYC_REJECTED\x10\x02\x12\x1f\n" +
	"\x1bKYC_NOT_PROCESSABLE_FOREVER\x10\x03\x12\x13\n" +
	"\x0fKYC_FIX_REQUEST\x10\x04\x12\x14\n" +
	"\x10KYC_ADMIN_DENIED\x10\x05\x12\x1c\n" +
	"\x18SUPPORT_TICKET_SUBMITTED\x10\x06\x12\x1f\n" +
	"\x1bBILLING_LOW_BALANCE_WARNING\x10\a\x12\x13\n" +
	"\x0fREFERRAL_SHARED\x10\b\x12\x1b\n" +
	"\x17ORGANIZATION_ONBOARDING\x10d\x12\x1a\n" +
	"\x16ORGANIZATION_NEW_ADMIN\x10e\x12\x17\n" +
	"\x12PARTNER_ONBOARDING\x10\xc8\x01B@Z>github.com/sologenic/com-fs-email-template-model;emailtemplateb\x06proto3"

var (
	file_emailtemplate_proto_rawDescOnce sync.Once
	file_emailtemplate_proto_rawDescData []byte
)

func file_emailtemplate_proto_rawDescGZIP() []byte {
	file_emailtemplate_proto_rawDescOnce.Do(func() {
		file_emailtemplate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_emailtemplate_proto_rawDesc), len(file_emailtemplate_proto_rawDesc)))
	})
	return file_emailtemplate_proto_rawDescData
}

var file_emailtemplate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_emailtemplate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_emailtemplate_proto_goTypes = []any{
	(EmailTemplateType)(0),        // 0: emailtemplate.EmailTemplateType
	(*EmailTemplate)(nil),         // 1: emailtemplate.EmailTemplate
	(*EmailTemplateDetails)(nil),  // 2: emailtemplate.EmailTemplateDetails
	(*EmailTemplates)(nil),        // 3: emailtemplate.EmailTemplates
	(*audit.Audit)(nil),           // 4: audit.Audit
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(metadata.Network)(0),         // 6: metadata.Network
}
var file_emailtemplate_proto_depIdxs = []int32{
	2, // 0: emailtemplate.EmailTemplate.EmailTemplate:type_name -> emailtemplate.EmailTemplateDetails
	4, // 1: emailtemplate.EmailTemplate.Audit:type_name -> audit.Audit
	0, // 2: emailtemplate.EmailTemplateDetails.Type:type_name -> emailtemplate.EmailTemplateType
	5, // 3: emailtemplate.EmailTemplateDetails.CreatedAt:type_name -> google.protobuf.Timestamp
	5, // 4: emailtemplate.EmailTemplateDetails.UpdatedAt:type_name -> google.protobuf.Timestamp
	6, // 5: emailtemplate.EmailTemplateDetails.Network:type_name -> metadata.Network
	1, // 6: emailtemplate.EmailTemplates.EmailTemplates:type_name -> emailtemplate.EmailTemplate
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_emailtemplate_proto_init() }
func file_emailtemplate_proto_init() {
	if File_emailtemplate_proto != nil {
		return
	}
	file_emailtemplate_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_emailtemplate_proto_rawDesc), len(file_emailtemplate_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_emailtemplate_proto_goTypes,
		DependencyIndexes: file_emailtemplate_proto_depIdxs,
		EnumInfos:         file_emailtemplate_proto_enumTypes,
		MessageInfos:      file_emailtemplate_proto_msgTypes,
	}.Build()
	File_emailtemplate_proto = out.File
	file_emailtemplate_proto_goTypes = nil
	file_emailtemplate_proto_depIdxs = nil
}
