// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.1
// source: emailtemplate.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Timestamp } from "./google/protobuf/timestamp";
import { Audit } from "./sologenic/com-fs-utils-lib/models/audit/audit";
import { Network, networkFromJSON, networkToJSON } from "./sologenic/com-fs-utils-lib/models/metadata/metadata";

export const protobufPackage = "emailtemplate";

export enum EmailTemplateType {
  NOT_USED_EMAIL_TEMPLATE_TYPE = 0,
  /**
   * KYC_APPROVED - KYC Email Templates (configurable by each organization)
   * Target: End User
   */
  KYC_APPROVED = 1,
  KYC_REJECTED = 2,
  KYC_NOT_PROCESSABLE_FOREVER = 3,
  KYC_FIX_REQUEST = 4,
  KYC_ADMIN_DENIED = 5,
  SUPPORT_TICKET_SUBMITTED = 6,
  /**
   * ORGANIZATION_ONBOARDING - Organization Templates (configurable by Sologenic Admin)
   * Target: Organization Admin
   */
  ORGANIZATION_ONBOARDING = 100,
  UNRECOGNIZED = -1,
}

export function emailTemplateTypeFromJSON(object: any): EmailTemplateType {
  switch (object) {
    case 0:
    case "NOT_USED_EMAIL_TEMPLATE_TYPE":
      return EmailTemplateType.NOT_USED_EMAIL_TEMPLATE_TYPE;
    case 1:
    case "KYC_APPROVED":
      return EmailTemplateType.KYC_APPROVED;
    case 2:
    case "KYC_REJECTED":
      return EmailTemplateType.KYC_REJECTED;
    case 3:
    case "KYC_NOT_PROCESSABLE_FOREVER":
      return EmailTemplateType.KYC_NOT_PROCESSABLE_FOREVER;
    case 4:
    case "KYC_FIX_REQUEST":
      return EmailTemplateType.KYC_FIX_REQUEST;
    case 5:
    case "KYC_ADMIN_DENIED":
      return EmailTemplateType.KYC_ADMIN_DENIED;
    case 6:
    case "SUPPORT_TICKET_SUBMITTED":
      return EmailTemplateType.SUPPORT_TICKET_SUBMITTED;
    case 100:
    case "ORGANIZATION_ONBOARDING":
      return EmailTemplateType.ORGANIZATION_ONBOARDING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EmailTemplateType.UNRECOGNIZED;
  }
}

export function emailTemplateTypeToJSON(object: EmailTemplateType): string {
  switch (object) {
    case EmailTemplateType.NOT_USED_EMAIL_TEMPLATE_TYPE:
      return "NOT_USED_EMAIL_TEMPLATE_TYPE";
    case EmailTemplateType.KYC_APPROVED:
      return "KYC_APPROVED";
    case EmailTemplateType.KYC_REJECTED:
      return "KYC_REJECTED";
    case EmailTemplateType.KYC_NOT_PROCESSABLE_FOREVER:
      return "KYC_NOT_PROCESSABLE_FOREVER";
    case EmailTemplateType.KYC_FIX_REQUEST:
      return "KYC_FIX_REQUEST";
    case EmailTemplateType.KYC_ADMIN_DENIED:
      return "KYC_ADMIN_DENIED";
    case EmailTemplateType.SUPPORT_TICKET_SUBMITTED:
      return "SUPPORT_TICKET_SUBMITTED";
    case EmailTemplateType.ORGANIZATION_ONBOARDING:
      return "ORGANIZATION_ONBOARDING";
    case EmailTemplateType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum Section {
  NOT_USED_EMAIL_SECTION = 0,
  SUBJECT = 1,
  HEADER = 2,
  /** BODY_INTRO - Greeting, introduction, etc. */
  BODY_INTRO = 3,
  /** BODY_MAIN - Main content of the email */
  BODY_MAIN = 4,
  /** BODY_DETAILS - Additional details or information if needed */
  BODY_DETAILS = 5,
  FOOTER = 6,
  SIGNATURE = 7,
  UNRECOGNIZED = -1,
}

export function sectionFromJSON(object: any): Section {
  switch (object) {
    case 0:
    case "NOT_USED_EMAIL_SECTION":
      return Section.NOT_USED_EMAIL_SECTION;
    case 1:
    case "SUBJECT":
      return Section.SUBJECT;
    case 2:
    case "HEADER":
      return Section.HEADER;
    case 3:
    case "BODY_INTRO":
      return Section.BODY_INTRO;
    case 4:
    case "BODY_MAIN":
      return Section.BODY_MAIN;
    case 5:
    case "BODY_DETAILS":
      return Section.BODY_DETAILS;
    case 6:
    case "FOOTER":
      return Section.FOOTER;
    case 7:
    case "SIGNATURE":
      return Section.SIGNATURE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Section.UNRECOGNIZED;
  }
}

export function sectionToJSON(object: Section): string {
  switch (object) {
    case Section.NOT_USED_EMAIL_SECTION:
      return "NOT_USED_EMAIL_SECTION";
    case Section.SUBJECT:
      return "SUBJECT";
    case Section.HEADER:
      return "HEADER";
    case Section.BODY_INTRO:
      return "BODY_INTRO";
    case Section.BODY_MAIN:
      return "BODY_MAIN";
    case Section.BODY_DETAILS:
      return "BODY_DETAILS";
    case Section.FOOTER:
      return "FOOTER";
    case Section.SIGNATURE:
      return "SIGNATURE";
    case Section.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Key: OrganizationID-Network-EmailTemplateType */
export interface EmailTemplate {
  EmailTemplate: EmailTemplateDetails | undefined;
  Audit: Audit | undefined;
}

export interface EmailTemplateDetails {
  Type: EmailTemplateType;
  /** If not set, this is a System template */
  OrganizationID?:
    | string
    | undefined;
  /** Display Name */
  Name: string;
  /** Email Subject */
  Subject: string;
  /** HTML content */
  HTML: string;
  /** Description for internal use */
  Description: string;
  /** fallback for HTML content */
  PlainText: string;
  /** Non-standard metadata: Network here is optional. In other cases it is almost always required */
  CreatedAt: Date | undefined;
  UpdatedAt: Date | undefined;
  Network?: Network | undefined;
  TextElements: TextElement[];
}

export interface EmailTemplates {
  EmailTemplates: EmailTemplate[];
}

export interface TextElement {
  /** Block identifier */
  Section: Section;
  /** The content text */
  Content: string;
}

function createBaseEmailTemplate(): EmailTemplate {
  return { EmailTemplate: undefined, Audit: undefined };
}

export const EmailTemplate = {
  encode(message: EmailTemplate, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.EmailTemplate !== undefined) {
      EmailTemplateDetails.encode(message.EmailTemplate, writer.uint32(10).fork()).ldelim();
    }
    if (message.Audit !== undefined) {
      Audit.encode(message.Audit, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): EmailTemplate {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmailTemplate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.EmailTemplate = EmailTemplateDetails.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.Audit = Audit.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmailTemplate {
    return {
      EmailTemplate: isSet(object.EmailTemplate) ? EmailTemplateDetails.fromJSON(object.EmailTemplate) : undefined,
      Audit: isSet(object.Audit) ? Audit.fromJSON(object.Audit) : undefined,
    };
  },

  toJSON(message: EmailTemplate): unknown {
    const obj: any = {};
    if (message.EmailTemplate !== undefined) {
      obj.EmailTemplate = EmailTemplateDetails.toJSON(message.EmailTemplate);
    }
    if (message.Audit !== undefined) {
      obj.Audit = Audit.toJSON(message.Audit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmailTemplate>, I>>(base?: I): EmailTemplate {
    return EmailTemplate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmailTemplate>, I>>(object: I): EmailTemplate {
    const message = createBaseEmailTemplate();
    message.EmailTemplate = (object.EmailTemplate !== undefined && object.EmailTemplate !== null)
      ? EmailTemplateDetails.fromPartial(object.EmailTemplate)
      : undefined;
    message.Audit = (object.Audit !== undefined && object.Audit !== null) ? Audit.fromPartial(object.Audit) : undefined;
    return message;
  },
};

function createBaseEmailTemplateDetails(): EmailTemplateDetails {
  return {
    Type: 0,
    OrganizationID: undefined,
    Name: "",
    Subject: "",
    HTML: "",
    Description: "",
    PlainText: "",
    CreatedAt: undefined,
    UpdatedAt: undefined,
    Network: undefined,
    TextElements: [],
  };
}

export const EmailTemplateDetails = {
  encode(message: EmailTemplateDetails, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Type !== 0) {
      writer.uint32(8).int32(message.Type);
    }
    if (message.OrganizationID !== undefined) {
      writer.uint32(18).string(message.OrganizationID);
    }
    if (message.Name !== "") {
      writer.uint32(26).string(message.Name);
    }
    if (message.Subject !== "") {
      writer.uint32(34).string(message.Subject);
    }
    if (message.HTML !== "") {
      writer.uint32(42).string(message.HTML);
    }
    if (message.Description !== "") {
      writer.uint32(50).string(message.Description);
    }
    if (message.PlainText !== "") {
      writer.uint32(58).string(message.PlainText);
    }
    if (message.CreatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.CreatedAt), writer.uint32(66).fork()).ldelim();
    }
    if (message.UpdatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.UpdatedAt), writer.uint32(74).fork()).ldelim();
    }
    if (message.Network !== undefined) {
      writer.uint32(80).int32(message.Network);
    }
    for (const v of message.TextElements) {
      TextElement.encode(v!, writer.uint32(90).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): EmailTemplateDetails {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmailTemplateDetails();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.Type = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.Name = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.Subject = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.HTML = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.Description = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.PlainText = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.CreatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.UpdatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.TextElements.push(TextElement.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmailTemplateDetails {
    return {
      Type: isSet(object.Type) ? emailTemplateTypeFromJSON(object.Type) : 0,
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : undefined,
      Name: isSet(object.Name) ? globalThis.String(object.Name) : "",
      Subject: isSet(object.Subject) ? globalThis.String(object.Subject) : "",
      HTML: isSet(object.HTML) ? globalThis.String(object.HTML) : "",
      Description: isSet(object.Description) ? globalThis.String(object.Description) : "",
      PlainText: isSet(object.PlainText) ? globalThis.String(object.PlainText) : "",
      CreatedAt: isSet(object.CreatedAt) ? fromJsonTimestamp(object.CreatedAt) : undefined,
      UpdatedAt: isSet(object.UpdatedAt) ? fromJsonTimestamp(object.UpdatedAt) : undefined,
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : undefined,
      TextElements: globalThis.Array.isArray(object?.TextElements)
        ? object.TextElements.map((e: any) => TextElement.fromJSON(e))
        : [],
    };
  },

  toJSON(message: EmailTemplateDetails): unknown {
    const obj: any = {};
    if (message.Type !== 0) {
      obj.Type = emailTemplateTypeToJSON(message.Type);
    }
    if (message.OrganizationID !== undefined) {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.Name !== "") {
      obj.Name = message.Name;
    }
    if (message.Subject !== "") {
      obj.Subject = message.Subject;
    }
    if (message.HTML !== "") {
      obj.HTML = message.HTML;
    }
    if (message.Description !== "") {
      obj.Description = message.Description;
    }
    if (message.PlainText !== "") {
      obj.PlainText = message.PlainText;
    }
    if (message.CreatedAt !== undefined) {
      obj.CreatedAt = message.CreatedAt.toISOString();
    }
    if (message.UpdatedAt !== undefined) {
      obj.UpdatedAt = message.UpdatedAt.toISOString();
    }
    if (message.Network !== undefined) {
      obj.Network = networkToJSON(message.Network);
    }
    if (message.TextElements?.length) {
      obj.TextElements = message.TextElements.map((e) => TextElement.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmailTemplateDetails>, I>>(base?: I): EmailTemplateDetails {
    return EmailTemplateDetails.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmailTemplateDetails>, I>>(object: I): EmailTemplateDetails {
    const message = createBaseEmailTemplateDetails();
    message.Type = object.Type ?? 0;
    message.OrganizationID = object.OrganizationID ?? undefined;
    message.Name = object.Name ?? "";
    message.Subject = object.Subject ?? "";
    message.HTML = object.HTML ?? "";
    message.Description = object.Description ?? "";
    message.PlainText = object.PlainText ?? "";
    message.CreatedAt = object.CreatedAt ?? undefined;
    message.UpdatedAt = object.UpdatedAt ?? undefined;
    message.Network = object.Network ?? undefined;
    message.TextElements = object.TextElements?.map((e) => TextElement.fromPartial(e)) || [];
    return message;
  },
};

function createBaseEmailTemplates(): EmailTemplates {
  return { EmailTemplates: [] };
}

export const EmailTemplates = {
  encode(message: EmailTemplates, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.EmailTemplates) {
      EmailTemplate.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): EmailTemplates {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmailTemplates();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.EmailTemplates.push(EmailTemplate.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmailTemplates {
    return {
      EmailTemplates: globalThis.Array.isArray(object?.EmailTemplates)
        ? object.EmailTemplates.map((e: any) => EmailTemplate.fromJSON(e))
        : [],
    };
  },

  toJSON(message: EmailTemplates): unknown {
    const obj: any = {};
    if (message.EmailTemplates?.length) {
      obj.EmailTemplates = message.EmailTemplates.map((e) => EmailTemplate.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmailTemplates>, I>>(base?: I): EmailTemplates {
    return EmailTemplates.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmailTemplates>, I>>(object: I): EmailTemplates {
    const message = createBaseEmailTemplates();
    message.EmailTemplates = object.EmailTemplates?.map((e) => EmailTemplate.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTextElement(): TextElement {
  return { Section: 0, Content: "" };
}

export const TextElement = {
  encode(message: TextElement, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Section !== 0) {
      writer.uint32(8).int32(message.Section);
    }
    if (message.Content !== "") {
      writer.uint32(18).string(message.Content);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TextElement {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTextElement();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.Section = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Content = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TextElement {
    return {
      Section: isSet(object.Section) ? sectionFromJSON(object.Section) : 0,
      Content: isSet(object.Content) ? globalThis.String(object.Content) : "",
    };
  },

  toJSON(message: TextElement): unknown {
    const obj: any = {};
    if (message.Section !== 0) {
      obj.Section = sectionToJSON(message.Section);
    }
    if (message.Content !== "") {
      obj.Content = message.Content;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TextElement>, I>>(base?: I): TextElement {
    return TextElement.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TextElement>, I>>(object: I): TextElement {
    const message = createBaseTextElement();
    message.Section = object.Section ?? 0;
    message.Content = object.Content ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
