// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package emailtemplate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmailTemplateServiceClient is the client API for EmailTemplateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmailTemplateServiceClient interface {
	Get(ctx context.Context, in *EmailTemplateID, opts ...grpc.CallOption) (*EmailTemplate, error)
	List(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*EmailTemplates, error)
	Upsert(ctx context.Context, in *EmailTemplate, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Use cases:
	// 1. Delete a default template (Sologenic Admin only)
	// 2. Delete an organization specific template to revert to default (Organization Admin only)
	Delete(ctx context.Context, in *EmailTemplate, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type emailTemplateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailTemplateServiceClient(cc grpc.ClientConnInterface) EmailTemplateServiceClient {
	return &emailTemplateServiceClient{cc}
}

func (c *emailTemplateServiceClient) Get(ctx context.Context, in *EmailTemplateID, opts ...grpc.CallOption) (*EmailTemplate, error) {
	out := new(EmailTemplate)
	err := c.cc.Invoke(ctx, "/emailtemplate.EmailTemplateService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailTemplateServiceClient) List(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*EmailTemplates, error) {
	out := new(EmailTemplates)
	err := c.cc.Invoke(ctx, "/emailtemplate.EmailTemplateService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailTemplateServiceClient) Upsert(ctx context.Context, in *EmailTemplate, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/emailtemplate.EmailTemplateService/Upsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailTemplateServiceClient) Delete(ctx context.Context, in *EmailTemplate, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/emailtemplate.EmailTemplateService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailTemplateServiceServer is the server API for EmailTemplateService service.
// All implementations should embed UnimplementedEmailTemplateServiceServer
// for forward compatibility
type EmailTemplateServiceServer interface {
	Get(context.Context, *EmailTemplateID) (*EmailTemplate, error)
	List(context.Context, *Filter) (*EmailTemplates, error)
	Upsert(context.Context, *EmailTemplate) (*emptypb.Empty, error)
	// Use cases:
	// 1. Delete a default template (Sologenic Admin only)
	// 2. Delete an organization specific template to revert to default (Organization Admin only)
	Delete(context.Context, *EmailTemplate) (*emptypb.Empty, error)
}

// UnimplementedEmailTemplateServiceServer should be embedded to have forward compatible implementations.
type UnimplementedEmailTemplateServiceServer struct {
}

func (UnimplementedEmailTemplateServiceServer) Get(context.Context, *EmailTemplateID) (*EmailTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedEmailTemplateServiceServer) List(context.Context, *Filter) (*EmailTemplates, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedEmailTemplateServiceServer) Upsert(context.Context, *EmailTemplate) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedEmailTemplateServiceServer) Delete(context.Context, *EmailTemplate) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

// UnsafeEmailTemplateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailTemplateServiceServer will
// result in compilation errors.
type UnsafeEmailTemplateServiceServer interface {
	mustEmbedUnimplementedEmailTemplateServiceServer()
}

func RegisterEmailTemplateServiceServer(s grpc.ServiceRegistrar, srv EmailTemplateServiceServer) {
	s.RegisterService(&EmailTemplateService_ServiceDesc, srv)
}

func _EmailTemplateService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailTemplateID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailTemplateServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emailtemplate.EmailTemplateService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailTemplateServiceServer).Get(ctx, req.(*EmailTemplateID))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailTemplateService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailTemplateServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emailtemplate.EmailTemplateService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailTemplateServiceServer).List(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailTemplateService_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailTemplate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailTemplateServiceServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emailtemplate.EmailTemplateService/Upsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailTemplateServiceServer).Upsert(ctx, req.(*EmailTemplate))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailTemplateService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailTemplate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailTemplateServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emailtemplate.EmailTemplateService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailTemplateServiceServer).Delete(ctx, req.(*EmailTemplate))
	}
	return interceptor(ctx, in, info, handler)
}

// EmailTemplateService_ServiceDesc is the grpc.ServiceDesc for EmailTemplateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailTemplateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emailtemplate.EmailTemplateService",
	HandlerType: (*EmailTemplateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _EmailTemplateService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _EmailTemplateService_List_Handler,
		},
		{
			MethodName: "Upsert",
			Handler:    _EmailTemplateService_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _EmailTemplateService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emailtemplate-grpc.proto",
}
